name: Print Secrets and Variables

on:
  push:
    branches:
      - main

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
    - name: Print GitHub Secrets and Variables
      run: |
        echo "My Variable: ${{ vars.MY_VARIABLE }}"
        echo "My Secret: ${{ secrets.MY_SECRET }}"
