name: Run Tests for CI/CD

# Trigger workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.8
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        pip install -r requirements.txt; fi

    # Step 4: Run pytest to execute the tests
    - name: Run tests
      run: |
        pytest

  secret:
    runs-on: ubuntu-latest
    steps:
      # Step 5: Print GitHub Secrets and Variables  
      - name: Print GitHub Secrets and Variables
        run: |
          echo "My Variable: ${{ vars.MY_VARIABLE }}"
          echo "My Secret: ${{ secrets.MY_SECRET }}"
